displayName=AFK Hider
author=Filofteia
description=Change the client’s opacity after clicking specified actions
tags=afk,utility,toolbar,skilling
plugins=filo.afk.opacity.AFKOpacityPlugin
build=standard