displayName=CM Storage Presets
author=Filofteia
description=An Inventory Setups equivalent for Challenge Mode CoX
tags=Chambers,CM,UI,Inventory,Storage
plugins=filo.cm.checklist.CMChecklistPlugin
build=standard